pipeline:
  docker:
    image: alpine
    commands:
      - echo $DOCKER_USERNAME
      - echo $GEMFURY_TOKEN
    #repo: gregcook/docker-test
    #tags: test
    secrets: [ docker_username, docker_password, gemfury_token ]
